Add Non-Lag v6 Topologies to GCU Dynamic ACL Non-Lag List (#22575) (#23333)
The non-lag list of topologies in the GCU test_dynamic_acl test is
missing the v6 topologies, resulting in improper accounting of the
upstream ports on those tests, yielding the following error when trying
to reference an index of the upstream ports (upstream_ports[0]):
IndexError: list index out of range

Signed-off-by: Christopher Croy <ccroy@arista.com>
Signed-off-by: mssonicbld <sonicbld@microsoft.com>
Co-authored-by: Chris <156943338+ccroy-arista@users.noreply.github.com>